### ISSUE TITLE
[What's New] Quote structure

### ISSUE THREAD

**Issue by yatil** [w3c/wai-intro-wcag#14]
The quotes look weird to me. Due to the visual and the code, I assumed “Problem“ and “Works well“ was part of the quote.

```html 
<blockquote class="quotes">
  <p>Problem: "I can't rotate my tablet —  it's attached to my wheelchair."</p>
  <p>Works well: "The application works whether I  attach my tablet horizontally or vertically."</p>
</blockquote>
```

If we keep that structure I think the html should be (`<q>` element adds quotes automatically):

```html
<ul>
<li>Problem: <q>I can't rotate my tablet —  it's attached to my wheelchair.</q></li>
<li>Works well: <q>The application works whether I  attach my tablet horizontally or vertically.</q></li>
</ul>
```

It also feels weird that the text before the quote(s) is italic, but the quote is not. I wasn’t making the connection because of the formatting.

I think it would be good to have a heading “persona quote”. 

And I wonder if we want to merge the quotes into one: <q>My tablet is attached to my wheelchair and I can’t rotate it. That means that applications need to work whether I attach my tablet in portrait or landscape orientation.</q>

**Comment by slhenry** [comment]
Left to do:

- [ ] Spacing between quotes (undo <br><br> hack and do it right :-)
- [ ] ...

**Comment by yatil** [comment]
@slhenry I also removed the right margin from the blockquote, the occasional words sticking out to the right of the boxes looked broken.

**Comment by yatil** [comment]
Reopened without comment?

**Comment by slhenry** [comment]
(had sent in email :-)
