### ISSUE TITLE
Correct tag for the title of "fixed" banners (cookie consent, notifications, etc.)

### ISSUE THREAD

**Issue by collimarco** [w3c/wai-intro-wcag#143]
For "fixed" dialogs displayed on the page, like a "cookie consent banner" or "subscribe to notifications", what is the recommended tag for the title? 

Is it correct to use h1 to separate it from the main content?

Or another tag is more appropriate?

**Comment by shawna-slh** [comment]
Hi @collimarco

We host a W3C WAI Interest Group discussion list where issues of digital accessibility are discussed. From there you can get multiple perspectives.

You can look through the mailing list archives, to get a feel for the list, through: http://lists.w3.org/Archives/Public/w3c-wai-ig/

You can join the mailing list and post questions by following the instructions for the Discussion List under:
	https://www.w3.org/WAI/about/groups/waiig/#mailinglist
