### ISSUE TITLE
Remove "attention deficit hyperactivity disorder" from  text spacing persona

### ISSUE THREAD

**Issue by lauracarlson** [w3c/wai-intro-wcag#18]
Hi Shawn,

As I mentioned in last week's LVTF meeting, the text "attention deficit hyperactivity disorder" should be removed from the text spacing persona as we have no research that  supports ADHD. We only have research for dyslexia and low vision. Details are in the understanding doc resources section.

Thanks,
Laura

**Comment by slhenry** [comment]
Done. https://github.com/w3c/wai-intro-wcag/commit/6ee57538cdc0e3e975ac8378115ac114dbaa7047#diff-ec04d7d9c0c20b1dd304bfebb429e1e1
