### ISSUE TITLE
[Overview page] Edit needed about 2.2 publishing [low priority] 

### ISSUE THREAD

**Issue by lbeaze** [w3c/wai-intro-wcag#270]
The following sentence (on the [overview page](The following sentence [on the overview](https://www.w3.org/WAI/standards-guidelines/wcag/non-web-ict/) needs an edit to reflect the true state of 2.2 publishing. 

"WCAG 2.1 was published in 2018 and WCAG 2.2 may be published in 2023." 

)) needs an edit to reflect the true state of 2.2 publishing. 

"WCAG 2.1 was published in 2018 and WCAG 2.2 may be published in 2023."

**Comment by shawna-slh** [comment]
thanks @lbeaze !
