### ISSUE TITLE
[low-medium priority] breadcrumb bug

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-intro-wcag#29]
https://www.w3.org/WAI/standards-guidelines/wcag/20/glance/

**Comment by slhenry** [comment]
also noticed it's wrong on this page:
https://www.w3.org/WAI/business-case/acknowledgements/

guess it's an overall issue, yet thought I'd give you another example in case it's helpful :-)

**Comment by yatil** [comment]
I moved this bug to the main website repo as it has to do with the templating, not with individual resources. https://github.com/w3c/wai-website/issues/118
