### ISSUE TITLE
"WCAG 2.1 at a Glance" links broken

### ISSUE THREAD

**Issue by clubajax** [w3c/wai-intro-wcag#31]
https://www.w3.org/WAI/standards-guidelines/wcag/glance/

All or most of the anchor tags on this page appear to be wrong or outdated.

**Comment by yatil** [comment]
@clubajax Thanks for mentioning, I’ll see what went wrong there… Sorry for the inconvenience.

**Comment by yatil** [comment]
@clubajax I have uploaded a new version of the quick reference that includes recognition for the older IDs used in the Glance document. Thanks again for the bug report.
