### ISSUE TITLE
[!! New in 2.1]  Tiny typo in persona quote for 1.3.5? 

### ISSUE THREAD

**Issue by goodwitch** [w3c/wai-intro-wcag#6]
I think there may be a typo in the persona quote for WCAG 2.1 SC 1.3.5.  I suggest putting the word "to" just before the word "work" in the last sentence:

- **current text:** Works well: "I love websites that can automatically fill it all in for me. Then I don't have work so hard to get the numbers and spelling right."
- **proposed change:** Works well: "I love websites that can automatically fill it all in for me. Then I don't have **to** work so hard to get the numbers and spelling right."

**Comment by slhenry** [comment]
Fixed! Thanks!
