### ISSUE TITLE
[!! New in 2.1] Persona name / no name

### ISSUE THREAD

**Issue by notabene** [w3c/wai-intro-wcag#7]
Problem:
* It feels strange that some personas were named and some not.

Correction:
* Either add names when they're missing
* Or remove names altogether.

My preference goes with adding the missing names as it helps (I think) personify the concept (like the nice “OK I know I'm a geek” one persona says, for example).

PS: I saw the footnote but assuming it won't be in final document, it feels strange. As usual, feel free to ignore my remarks etc. ;)

**Comment by slhenry** [comment]
Good point, Stephane. I'm writing up the issue and will get more input on it.

p.s. I was planning to leave the [About the Persona Quotes section](https://w3c.github.io/wai-intro-wcag/standards-guidelines/wcag/new-in-21/#about-the-personas-quotes)

However, I still think it's good to address the issue. :-)

**Comment by slhenry** [comment]
Here's about the issue: <https://github.com/w3c/wai-intro-wcag/wiki/Persona-names>

I've added roles to https://w3c.github.io/wai-intro-wcag/standards-guidelines/wcag/new-in-21/

I'll send an update email to folks about it.

Thanks again for the input (even though it did cause lots more work ;-).

**Comment by notabene** [comment]
On 2018-05-28 22:05, shawn_slh wrote:

> I've added roles to
> https://w3c.github.io/wai-intro-wcag/standards-guidelines/wcag/new-in-21/
> 
> I'll send an update email to folks about it.
> 
> Thanks again for the input (even though it did cause lots more work
> ;-).

Hah, sorry about that ;)

Great job, Shawn!
